
module.exports = {
  "replaceAttrValues": {
    "#2B2B2B": "{props.border}",
    "#e5e5e1": "{props.hair}",
    "#e4e4e4": "{props.face}",
    "#e6e6e6": "{props.neck}",
    "#e7e7e7": "{props.traps}",
    "#e8e8e8": "{props.upperBack}",
    "#e9e9e9": "{props.delts}",
    "#ededed": "{props.scapula}",
    "#eeeeee": "{props.pecs}",
    "#eaeaea": "{props.triceps}",
    "#ebebeb": "{props.lats}",
    "#f0f0f0": "{props.biceps}",
    "#ececec": "{props.obliques}",
    "#f3f3f3": "{props.abs}",
    "#f2f2f2": "{props.forearms}",
    "#f4f4f4": "{props.lowerBack}",
    "#f5f5f5": "{props.lowerCore}",
    "#f6f6f6": "{props.abductors}",
    "#f7f7f7": "{props.ass}",
    "#f8f8f8": "{props.quads}",
    "#f9f9f9": "{props.hands}",
    "#fafafa": "{props.hamstrings}",
    "#fbfbfb": "{props.knees}",
    "#fcfcfc": "{props.backKnee}",
    "#fdfdfd": "{props.shins}",
    "#fefefe": "{props.calves}",
    "#e5e5e5": "{props.foot}",
    "#ffffff": "{props.fillAll}"
  }
}

    /*
    [props.border}"{props.fill}",
    [props.hair}"{props.fill}",
    [props.face}"{props.fill}",
    [props.neck}"{props.fill}",
    [props.traps}"{props.fill}",
    [props.upperBack}"{props.fill}",
    [props.delts}"{props.fill}",
    [props.scapula}"{props.fill}",
    [props.pecs}"{props.fill}",
    [props.triceps}"{props.fill}",
    [props.lats}"{props.fill}",
    [props.biceps}"{props.fill}",
    [props.obliques}"{props.fill}",
    [props.abs}"{props.fill}",
    [props.forearms}"{props.fill}",
    [props.lowerBack}"{props.fill}",
    [props.lowerCore}"{props.fill}",
    [props.abductors}"{props.fill}",
    [props.ass}"{props.fill}",
    [props.quads}"{props.fill}",
    [props.hands}"{props.fill}",
    [props.hamstrings}"{props.fill}",
    [props.knees}"{props.fill}",
    [props.backKnee}"{props.fill}" ,
    [props.shins}"{props.fill}",
    [props.calves}"{props.fill}",
    [props.foot}"{props.fill}"*/