module.exports = {
  "replaceAttrValues": {
    "#2B2B2B": "{props.border}",
    "#e5e5e1": "{props.hair}",
    "#e4e4e4": "{props.face}",
    "#e6e6e6": "{props.neck}",
    "#e7e7e7": "{props.traps}",
    "#e8e8e8": "{props.upperBack}",
    "#e9e9e9": "{props.delts}",
    "#ededed": "{props.scapula}",
    "#eeeeee": "{props.pecs}",
    "#eaeaea": "{props.triceps}",
    "#ebebeb": "{props.lats}",
    "#f0f0f0": "{props.biceps}",
    "#ececec": "{props.obliques}",
    "#f3f3f3": "{props.abs}",
    "#f2f2f2": "{props.forearms}",
    "#f4f4f4": "{props.lowerBack}",
    "#f5f5f5": "{props.lowerCore}",
    "#f6f6f6": "{props.abductors}",
    "#f7f7f7": "{props.ass}",
    "#f8f8f8": "{props.quads}",
    "#f9f9f9": "{props.hands}",
    "#fafafa": "{props.hamstrings}",
    "#fbfbfb": "{props.knees}",
    "#fcfcfc": "{props.backKnee}",
    "#fdfdfd": "{props.shins}",
    "#fefefe": "{props.calves}",
    "#e5e5e5": "{props.foot}",
    "#ffffff": "{props.fillAll}"
  }
}