module.exports = {
  "replaceAttrValues": {
    "#2B2B2B": "{props.Border}",
    "#e5e5e1": "{props.Hair}",
    "#e4e4e4": "{props.Face}",
    "#e6e6e6": "{props.Neck}",
    "#e7e7e7": "{props.Traps}",
    "#e8e8e8": "{props.Upper_Back}",
    "#e9e9e9": "{props.Shoulders}",
    "#ededed": "{props.Scapula}",
    "#eeeeee": "{props.Pectorals}",
    "#eaeaea": "{props.Triceps}",
    "#ebebeb": "{props.Lats}",
    "#f0f0f0": "{props.Biceps}",
    "#ececec": "{props.Obliques}",
    "#f3f3f3": "{props.Abs}",
    "#f2f2f2": "{props.Forearms}",
    "#f4f4f4": "{props.Lower_Back}",
    "#f5f5f5": "{props.Lower_Core}",
    "#f6f6f6": "{props.Abductors}",
    "#f7f7f7": "{props.Ass}",
    "#f8f8f8": "{props.Quadriceps}",
    "#f9f9f9": "{props.Hands}",
    "#fafafa": "{props.Hamstrings}",
    "#fbfbfb": "{props.Knees}",
    "#fcfcfc": "{props.Back_Knee}",
    "#fdfdfd": "{props.Shins}",
    "#fefefe": "{props.Calves}",
    "#e5e5e5": "{props.Foot}",
    "#ffffff": "{props.FillAll}"
  }
}